apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: shared-nvswitch-device-plugin
  namespace: nvidia-gpu-operator
  labels:
    app: shared-nvswitch-device-plugin
spec:
  selector:
    matchLabels:
      name: shared-nvswitch-device-plugin
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: shared-nvswitch-device-plugin
        app: shared-nvswitch-device-plugin
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      hostNetwork: true
      hostPID: true
      priorityClassName: system-node-critical
      serviceAccountName: shared-nvswitch-device-plugin
      containers:
      - name: shared-nvswitch-device-plugin
        image: quay.io/mresvani/shared-nvswitch-gpu-device-plugin:latest
        imagePullPolicy: Always
        command:
        - ./device-plugin
        args:
        - --config-path=/etc/shared-nvswitch-device-plugin/config.yaml
        - --log-level=info
        securityContext:
          privileged: true
          seLinuxOptions:
            level: s0
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 500m
            memory: 200Mi
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: proc
          mountPath: /proc
          readOnly: true
        - name: config
          mountPath: /etc/shared-nvswitch-device-plugin
          readOnly: true
        - name: nvidia-fabricmanager
          mountPath: /var/run/nvidia-fabricmanager
        ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
          type: DirectoryOrCreate
      - name: dev
        hostPath:
          path: /dev
          type: Directory
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      - name: config
        configMap:
          name: shared-nvswitch-device-plugin-config
      - name: nvidia-fabricmanager
        hostPath:
          path: /var/run/nvidia-fabricmanager
          type: DirectoryOrCreate
      terminationGracePeriodSeconds: 30
