apiVersion: v1
kind: ServiceAccount
metadata:
  name: shared-nvswitch-device-plugin
  namespace: nvidia-gpu-operator
  labels:
    app: shared-nvswitch-device-plugin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shared-nvswitch-device-plugin
  labels:
    app: shared-nvswitch-device-plugin
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shared-nvswitch-device-plugin
  labels:
    app: shared-nvswitch-device-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shared-nvswitch-device-plugin
subjects:
- kind: ServiceAccount
  name: shared-nvswitch-device-plugin
  namespace: nvidia-gpu-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shared-nvswitch-device-plugin
  namespace: nvidia-gpu-operator
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shared-nvswitch-device-plugin
  namespace: nvidia-gpu-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shared-nvswitch-device-plugin
subjects:
- kind: ServiceAccount
  name: shared-nvswitch-device-plugin
  namespace: nvidia-gpu-operator
