apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shared-nvswitch-device-plugin
  namespace: nvidia-gpu-operator
  labels:
    app: shared-nvswitch-device-plugin
    component: metrics
spec:
  selector:
    matchLabels:
      app: shared-nvswitch-device-plugin
      component: metrics
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
  namespaceSelector:
    matchNames:
    - nvidia-gpu-operator
