apiVersion: v1
kind: Service
metadata:
  name: shared-nvswitch-device-plugin-metrics
  namespace: kube-system
  labels:
    app: shared-nvswitch-device-plugin
    component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for DaemonSet
  selector:
    name: shared-nvswitch-device-plugin
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP